### ISSUE TITLE
Fix KMetroids

### ISSUE THREAD

**Issue by ElliottP-13** [cullingsj/Machine_Learning#14]
The current KMetroids does not work.

It will move all of the metroids to the center point of all of the data.

**HOW TO FIX**
1. Split the data up to ones that are closest to the metroid.
2. Move metroid to datapoint within the list that mimimizes cost
3. Repeat many times

**Comment by ElliottP-13** [comment]
Before you do this. Either make your branch off of my issue10 branch. Or Merge the Issue10 and 6 pull request

**Comment by cullingsj** [comment]
The closest points to the metroid logic is handled in the cost calculation. As far as moving to the center point I had an argument missing in the inner most for loop of runIteration(). Should be functional now in branch issue14
